### ISSUE TITLE
How to add Infinite loop in ViewPager

### ISSUE THREAD

**Issue by jahangirkabir** [noundla/Sunny_Projects#1]
Is it possible to add InfiniteViewPager with this? How?

**Comment by noundla** [comment]
I have a sample like below. Please have a look into this.
Assume that you have 5 pages to display and the List will contains the indexes as 0,1,2,3,4. 
To enable the infinite loop do like this.
create List with items as 4,0,1,2,3,4,0 . When you reach the last item means(0, which is at last position now.) set the current position as first available 0(means the second item). Same appilcable for the 4th one. I have done this procedure in one of my iOS project. Please work like that and let me know if any issues.
